# pixel space task
pixel:
  mcmc_sampler_config:  
    mcmc_sampler_config:  
    num_steps: 100
    lr: 5e-5
    tau: 0.01
    lr_min_ratio: 0.01
    mc_algo: langevin
    prior_solver: gaussian
    rho: 0.005  # Face loss weight
    num_steps_fs: 10  # Face similarity steps
    norm_order_fs: 1  # Face loss norm order
    use_face_similarity: True
  
  operator:
    name: inpainting
    mask_type: box
    mask_len_range: [128, 129]
    resolution: 256
    sigma: 0.05

# latent diffusion model
ldm: 
  mcmc_sampler_config: 
    num_steps: 15
    lr: 9.02e-6
    tau: 0.01
    lr_min_ratio: 0.13
    momentum: 0.74
    mc_algo: hmc
    prior_solver: gaussian
  
  operator:
    name: inpainting
    mask_type: box
    mask_len_range: [128, 129]
    resolution: 256
    sigma: 0.05

# stable diffusion 
sd: 
  mcmc_sampler_config: 
    num_steps: 20
    lr: 1e-5
    tau: 0.01
    lr_min_ratio: 1
    momentum: 0.60
    mc_algo: hmc
    prior_solver: gaussian
  
  operator:
    name: inpainting
    mask_type: box
    mask_len_range: [128, 129]
    resolution: 256
    sigma: 0.01