# pixel space task
pixel:
  mcmc_sampler_config:  
    num_steps: 100
    lr: 5e-5
    tau: 0.01
    lr_min_ratio: 0.01
    mc_algo: langevin
    prior_solver: gaussian
    rho: 0.0005  # Face loss weight
    num_steps_fs: 10  # Face similarity steps
    norm_order_fs: 2  # Face loss norm order
    use_face_similarity: True
  
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5
    sigma: 0.05

# latent diffusion model
ldm: 
  mcmc_sampler_config: 
    num_steps: 49
    lr: 2.4e-5 
    tau: 0.01
    lr_min_ratio: 0.041
    momentum: 0.45
    mc_algo: hmc
    prior_solver: gaussian
  
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5
    sigma: 0.05

# stable diffusion 
sd: 
  mcmc_sampler_config: 
    num_steps: 30
    lr: 2e-5
    tau: 0.01
    lr_min_ratio: 1
    momentum: 0.85
    mc_algo: hmc
    prior_solver: gaussian
  
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5
    sigma: 0.01