# pixel space task
pixel:
  mcmc_sampler_config:  
    num_steps: 100
    lr: 5e-5
    tau: 0.01
    lr_min_ratio: 0.01
    mc_algo: langevin
    prior_solver: gaussian
    use_face_similarity: False
  
  operator:
    name: phase_retrieval
    oversample: 2.0
    sigma: 0.05

# latent diffusion model
ldm: 
  mcmc_sampler_config: 
    num_steps: 65
    lr: 2.1e-5
    tau: 0.01
    lr_min_ratio: 0.12
    momentum: 0.41
    mc_algo: hmc
    prior_solver: gaussian

  operator:
    name: phase_retrieval
    oversample: 2.0
    sigma: 0.05

# stable diffusion 
sd: 
  mcmc_sampler_config: 
    num_steps: 100
    lr: 7e-5 
    tau: 0.01
    lr_min_ratio: 1
    momentum: 0.70
    mc_algo: hmc
    prior_solver: gaussian

  operator:
    name: phase_retrieval
    oversample: 2.0
    sigma: 0.01